// <auto-generated />
using System;
using Galeri.Repository.AppDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galeri.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Galeri.Core.Models.Araçlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Açıklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KmDurumu")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Marka")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Renk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ÜretimYılı")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Araçlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Açıklama = "Hasarsız",
                            Fiyat = 5250m,
                            KategoriId = 1,
                            KmDurumu = "125000",
                            Marka = "BMW",
                            Model = "3.20i",
                            Renk = "sarı",
                            ÜretimYılı = "2010"
                        },
                        new
                        {
                            Id = 2,
                            Açıklama = "Hasarlı",
                            Fiyat = 4250m,
                            KategoriId = 1,
                            KmDurumu = "150000",
                            Marka = "BMW",
                            Model = "5.20i",
                            Renk = "beyaz",
                            ÜretimYılı = "2009"
                        });
                });

            modelBuilder.Entity("Galeri.Core.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Hatchback"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Cabrio"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Elektrikli"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Suv"
                        });
                });

            modelBuilder.Entity("Galeri.Core.Models.Araçlar", b =>
                {
                    b.HasOne("Galeri.Core.Models.Kategori", "Kategori")
                        .WithMany("Araçlar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Galeri.Core.Models.Kategori", b =>
                {
                    b.Navigation("Araçlar");
                });
#pragma warning restore 612, 618
        }
    }
}
